### ISSUE TITLE
Rebuild all of the binaries for ARM/X86 and re-release.

### ISSUE THREAD

**Issue by jm3** [netik/UTCMenuClock#11]
The repo and README recommend downloading the app via the two linked downloads, however, both of those downloads, including the one labeled 1.2, actually download and install UTC Menu Clock version 1.0a — see attached screenshots.

The incorrectly-named download should be deleted, and a new download from the 1.2.3 version should be added (probably to the releases tab of the repo.

## installed with 1.1 installer
![installed with 1 1 installer](https://user-images.githubusercontent.com/12213/66521094-55b2ed80-ea9f-11e9-9388-81ca7a9dc5d2.png) 

## installed with 1.2 installer
![installed with 1 2 installer](https://user-images.githubusercontent.com/12213/66521097-577cb100-ea9f-11e9-9d71-e2f9e2cd98fa.png)

**Comment by netik** [comment]
I've rebuild this and replaced the downloads in downloads.

**Comment by core-code** [comment]
thanks!
