### ISSUE TITLE
Warning on launch - app can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by jm3** [netik/UTCMenuClock#12]
On the latest **OS X Catalina**, when launching the app, the following warning appears:

![warning](https://user-images.githubusercontent.com/12213/66521242-a1659700-ea9f-11e9-849f-76cef447d50a.png)

"UTCMenuClock 1.2.3 can’t be opened because Apple cannot check it for malicious software."

**Comment by faried** [comment]
Is that the app, or the installer?  Right-click on it in the Finder and select "Open" -- that should launch it with a warning.

**Comment by twocs** [comment]
Same issue still exists. The instructions state:
> NOTE: After you install this software, you still have to run it to use it:   
> Double-click "UTCMenuClock" in your /Applications folder. If you want it to 
start automatically every time you log in , click on the UTC clock in the menu 
bar and select "Open At Login"

Following these instructions literally will cause the above popup. Right clicking and selecting Open launches it. So the fix might be as simple as editing the instructions in the Readme.

**Comment by netik** [comment]
This isn't really a bug. This is a "I haven't paid apple for signing this software and it's open source." 

You can go into the security pane and click "Run Anyway."

In the future, I'll pay the apple tax for a key. Sorry! 

You can also download Xcode, build, and sign this app yourself if you wish.
