### ISSUE TITLE
Feature request: ISO-8601 date format override

### ISSUE THREAD

**Issue by dm8tbr** [netik/UTCMenuClock#14]
Would be nice to have it in the familiar 2021-03-01 format, left of the time. Essentially forming a compliant timestamp.
Most timestamps, I work with are formatted ISO-8601 compliant.

Nevertheless, this is already very useful for me, thanks for the work you put into it!

**Comment by ijoseph** [comment]
was just about to request this myself. Looks pretty simple to implement by messing with the date formatters, maybe I'll take a stab at it this weekend.

**Comment by netik** [comment]
Ah, yes, okay, excellent point.  We to use the iso 8601 formats.

**Comment by netik** [comment]
I have added a Copy as ISO8601 feature. Will also modify and place a override
