### ISSUE TITLE
Hidden behind the Notch on M1

### ISSUE THREAD

**Issue by spanktar** [netik/UTCMenuClock#15]
I've used this for years (thank you!) — On my new M1 mac, when I launch the app, nothing happens. I see it running in the Activity Monitor but there's nothing in the menu bar.  I do have a lot of stuff in my menu bar so it could potentially be hidden behind the notch, but I thought Apple fixed this issue.  Maybe the fix requires a code change to utilize the fix?

EDIT: I quit some menu bar apps and voila, it appeared, so I can confirm it's hiding behind the notch.

Anyway, I'd really like to keep using this because it's great!

**Comment by netik** [comment]
I just had the same problem on my new machine! Let me see if there is any way to detect and get around this!

**Comment by chris-martinelli** [comment]
Reporting from 2023 - issue resolved by closing some menu bar apps.
