### ISSUE TITLE
Time appears too low - lower than the default system date and time - in OS X 10.10.5 at least.

### ISSUE THREAD

**Issue by IshmaelYavitz** [netik/UTCMenuClock#6]
The difference in positioning is quite obvious on-screen - less so in this much-cropped screenshot.

I've underlined the default system date and time text to demonstrate that it cuts through the time shown by UTCMenuClock.

![utcmenuclock-text-is-lower-than-clock--os-x-10 10 5](https://cloud.githubusercontent.com/assets/14002822/9693445/625fb44a-5305-11e5-9a21-111bce192684.png)

I cracked open the code but have never written anything for OS X.  I didn't find an easy fix - e.g. no interface builder where I could just drag the element upwards a bit.

Thanks.

**Comment by netik** [comment]
Sorry to take so long to respond here, I just saw your message.

I too am on 10.10.5 and do not see this issue happening.

Are you using a different system font? Maybe the problem is that I am not detecting that. Moving the menu in interface builder won't help because the system is responsible for managing the menu bar, afaik.

**Comment by IshmaelYavitz** [comment]
> Sorry to take so long to respond here, I just saw your message.

No worries.

> I too am on 10.10.5 and do not see this issue happening.

Strange.

> Are you using a different system font?

No.  Everything is pretty stock, including the fonts.

**Comment by jkrehm** [comment]
I noticed the same thing after installing. El Capitan, 10.11.6. Stock fonts. It's just one pixel off, but still manages to be noticeable.

I haven't tried tinkering with the code yet to see if I can figure anything out.

![screenshot 2016-09-23 07 46 35](https://cloud.githubusercontent.com/assets/999845/18789994/f774f73a-8161-11e6-969c-1db3c00005cc.png)

**Comment by netik** [comment]
Hmm, this problem still exists on 10.10.5 and 10.11. I am going to see if there's a use system font call or something that can be done here.

**Comment by netik** [comment]
In El Capitan, 10.11.6, this appears to be fixed. Maybe it was an Apple issue with 3rd party menu items, but I can't repro anymore.
