### ISSUE TITLE
option to toggle 24-hour/12-hour time

### ISSUE THREAD

**Issue by gvt** [netik/UTCMenuClock#9]
It would be really nice to have an option to toggle between 24-hour/12-hour time. Currently UTCMenuClock only offers 24-hour time. There are some times, such as viewing log timestamps, where the UTC time is in 12-hour format; in this case I need to convert between 12-hour/24-hour which leads to mistakes at midnight and its the sort of guess-work that I use this tool to avoid.

Please consider adding this option. And thanks for making this! Its super useful.

**Comment by netik** [comment]
Hey, okay! Good idea.
I think I can do that this week.

**Comment by netik** [comment]
Alright, it's done. Git pull + recompile and you'll have what you want. If you need a binary, let me know.

**Comment by gvt** [comment]
Thanks! :)
